#!/bin/bash

set -x

HOST_IP=$(ifconfig | awk '/inet/ { print $2 }' | egrep -v '^fe|^127|^192|^172|::' | head -1)
HOST_IP=${IP#addr:}
IP=$HOST_IP

if [[ $HOSTNAME == "node"* ]] ; then
    #rightscale
    HOST_IP=$(grep $(hostname)_ext /etc/hosts | awk '{print $1}')
    IP=$HOST_IP
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
    # Mac OSX
    HOST_IP=$(docker run --net=host debian:jessie ip addr show|grep inet|grep eth0|awk '{print $2}'|awk -F'/' '{print $1}')
    IP=localhost
fi
echo "Installing CHE Eclipse IDE"
pip install requests
#install CHE
sudo docker run --rm -e CHE_HOST=$HOST_IP -e CHE_PORT=8081 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/data:/data eclipse/che start
echo "Setting up Project"

echo $IP

WORKSPACE=$(python "$PWD"/.startup/create-workspace.py "$IP")

echo $WORKSPACE
sleep 4
sudo mkdir -p /tmp/data/instance/data/workspaces/$WORKSPACE/datastax
sudo cp -r "$PWD"/ /tmp/data/instance/data/workspaces/$WORKSPACE/datastax
